export const categories = [
    {
        name: "Size",
        items: [
            { name: "Small", slug: "small" },
            { name: "Medium", slug: "medium" },
            { name: "Large", slug: "large" },
            { name: "Extra Large", slug: "extra-large" },
            { name: "XXL", slug: "xxl" },
            { name: "XXXL", slug: "xxxl" },
        ],
    },
    {
        name: "Color",
        items: [
            { name: "Red", slug: "red" },
            { name: "Blue", slug: "blue" },
            { name: "Green", slug: "green" },
            { name: "Black", slug: "black" },
            { name: "White", slug: "white" },
            { name: "Yellow", slug: "yellow" },
        ],
    },
    {
        name: "Brand",
        items: [
            { name: "Nike", slug: "nike" },
            { name: "Adidas", slug: "adidas" },
            { name: "Puma", slug: "puma" },
            { name: "Reebok", slug: "reebok" },
            { name: "Under Armour", slug: "under-armour" },
            { name: "New Balance", slug: "new-balance" },
        ],
    },
    {
        name: "Price Range",
        items: [
            { name: "Under $50", slug: "under-50" },
            { name: "$50 - $100", slug: "50-100" },
            { name: "$100 - $200", slug: "100-200" },
            { name: "$200 - $500", slug: "200-500" },
            { name: "$500 - $1000", slug: "500-1000" },
            { name: "Over $1000", slug: "over-1000" },
        ],
    },
    {
        name: "Discount",
        items: [
            { name: "10% Off or More", slug: "10-off" },
            { name: "20% Off or More", slug: "20-off" },
            { name: "30% Off or More", slug: "30-off" },
            { name: "40% Off or More", slug: "40-off" },
            { name: "50% Off or More", slug: "50-off" },
            { name: "60% Off or More", slug: "60-off" },
        ],
    },
    {
        name: "Availability",
        items: [
            { name: "In Stock", slug: "in-stock" },
            { name: "Out of Stock", slug: "out-of-stock" },
        ],
    },
];

export const products = [
    {
        id: "1",
        name: "Men's Running Shoes",
        description: "Lightweight and comfortable running shoes for men.",
        price: 99.99,
        brand: "Nike",
        category: "Footwear",
        color: ["Black", "White", "Blue"],
        size: ["US 9", "US 10", "US 11"],
        images: [
            "/products/card1.png",
            "/products/card2.png",
            "/products/card3.png",
            "/products/card4.png",
        ],
        thumbnail: "/products/card1.png",
        stockAvailability: "In Stock",
        discount: "10% Off",
        rating: 4.5,
        slug: "mens-running-shoes",
        sku: "NIKE12345",
        weight: 0.5,
        dimensions: {
            length: 30,
            width: 10,
            height: 15,
        },
        tags: ["running", "athletic", "shoes"],
    },
    {
        id: "2",
        name: "Women's Yoga Pants",
        description: "Stretchable and comfortable yoga pants for women.",
        price: 49.99,
        brand: "Adidas",
        category: "Activewear",
        color: ["Black", "Gray", "Purple"],
        size: ["XS", "S", "M", "L"],
        images: ["/products/card2.png", "/products/card2.png"],
        thumbnail: "/products/card2.png",
        stockAvailability: "In Stock",
        slug: "womens-yoga-pants",
        sku: "ADIDAS67890",
        weight: 0.4,
        dimensions: {
            length: 35,
            width: 12,
            height: 18,
        },
        tags: ["yoga", "activewear", "pants"],
    },
    {
        id: "3",
        name: "Men's Casual Shirt",
        description: "Stylish and comfortable casual shirt for men.",
        price: 29.99,
        brand: "Gap",
        category: "Clothing",
        color: ["White", "Blue", "Gray"],
        size: ["S", "M", "L", "XL"],
        images: ["/products/card3.png", "/products/card3.png"],
        thumbnail: "/products/card3.png",
        stockAvailability: "In Stock",
        slug: "mens-casual-shirt",
        sku: "GAP98765",
        weight: 0.3,
        dimensions: {
            length: 25,
            width: 10,
            height: 5,
        },
        tags: ["shirt", "casual", "clothing"],
    },
    {
        id: "4",
        name: "Women's Running Shorts",
        description: "Breathable and lightweight running shorts for women.",
        price: 39.99,
        brand: "Under Armour",
        category: "Activewear",
        color: ["Black", "Pink", "Purple"],
        size: ["XS", "S", "M", "L"],
        images: ["/products/card4.png", "/products/card4.png"],
        thumbnail: "/products/card4.png",
        stockAvailability: "In Stock",
        slug: "womens-running-shorts",
        sku: "UA56789",
        weight: 0.2,
        dimensions: {
            length: 20,
            width: 8,
            height: 3,
        },
        tags: ["running", "activewear", "shorts"],
    },
    {
        id: "5",
        name: "Men's Hoodie",
        description: "Warm and comfortable hoodie for men.",
        price: 79.99,
        brand: "The North Face",
        category: "Clothing",
        color: ["Black", "Gray", "Blue"],
        size: ["S", "M", "L", "XL"],
        images: ["/products/card1.png", "/products/card1.png"],
        thumbnail: "/products/card1.png",
        stockAvailability: "In Stock",
        slug: "mens-hoodie",
        sku: "TNF123",
        weight: 0.6,
        dimensions: {
            length: 40,
            width: 15,
            height: 10,
        },
        tags: ["hoodie", "clothing"],
    },
    {
        id: "6",
        name: "Wireless Bluetooth Earbuds",
        description:
            "High-quality wireless earbuds with Bluetooth connectivity.",
        price: 69.99,
        brand: "Sony",
        category: "Electronics",
        color: ["Black", "White", "Red"],
        size: ["One Size"],
        images: ["/products/card2.png", "/products/card2.png"],
        thumbnail: "/products/card2.png",
        stockAvailability: "In Stock",
        slug: "wireless-bluetooth-earbuds",
        sku: "SONY789",
        weight: 0.1,
        dimensions: {
            length: 5,
            width: 5,
            height: 2,
        },
        tags: ["earbuds", "audio", "electronics"],
    },
    {
        id: "7",
        name: "Portable Power Bank",
        description:
            "Compact and portable power bank for charging devices on the go.",
        price: 29.99,
        brand: "Anker",
        category: "Electronics",
        color: ["Black", "White", "Blue"],
        size: ["One Size"],
        images: ["/products/card3.png", "/products/card3.png"],
        thumbnail: "/products/card3.png",
        stockAvailability: "In Stock",
        slug: "portable-power-bank",
        sku: "ANK123",
        weight: 0.3,
        dimensions: {
            length: 10,
            width: 5,
            height: 2,
        },
        tags: ["power-bank", "electronics"],
    },
    {
        id: "8",
        name: "Men's Leather Wallet",
        description:
            "Classic leather wallet with multiple card slots and a cash compartment.",
        price: 49.99,
        brand: "Fossil",
        category: "Accessories",
        color: ["Black", "Brown"],
        size: ["One Size"],
        images: ["/products/card4.png", "/products/card4.png"],
        thumbnail: "/products/card4.png",
        stockAvailability: "In Stock",
        slug: "mens-leather-wallet",
        sku: "FOSSIL456",
        weight: 0.2,
        dimensions: {
            length: 10,
            width: 8,
            height: 2,
        },
        tags: ["wallet", "accessories"],
    },
    {
        id: "9",
        name: "Travel Backpack",
        description:
            "Durable and spacious backpack for travel and outdoor activities.",
        price: 79.99,
        brand: "Osprey",
        category: "Bags",
        color: ["Black", "Green", "Blue"],
        size: ["One Size"],
        images: ["/products/card2.png", "/products/card2.png"],
        thumbnail: "/products/card2.png",
        stockAvailability: "In Stock",
        slug: "travel-backpack",
        sku: "OSPREY789",
        weight: 1.0,
        dimensions: {
            length: 50,
            width: 30,
            height: 20,
        },
        tags: ["backpack", "bags", "travel"],
    },
    {
        id: "10",
        name: "Smartphone Case",
        description:
            "Protective case for smartphones with shock-absorbing features.",
        price: 19.99,
        brand: "Spigen",
        category: "Accessories",
        color: ["Black", "Clear", "Blue"],
        size: ["One Size"],
        images: ["/products/card1.png", "/products/card1.png"],
        thumbnail: "/products/card1.png",
        stockAvailability: "In Stock",
        slug: "smartphone-case",
        sku: "SPIGEN345",
        weight: 0.1,
        dimensions: {
            length: 15,
            width: 8,
            height: 1,
        },
        tags: ["smartphone-case", "accessories"],
    },
];

export const reviews = [
    // Reviews for product 1
    {
        productId: "1",
        userId: "user1",
        username: "JohnDoe",
        rating: 5,
        review: "These shoes are amazing! They are so comfortable and lightweight. Perfect for running or everyday wear.",
        date: new Date("2023-03-15"),
    },
    {
        productId: "1",
        userId: "user2",
        username: "JaneSmith",
        rating: 4,
        review: "Great shoes, but they run a bit small. I would recommend ordering a size up for a perfect fit.",
        date: new Date("2023-03-20"),
    },
    // Reviews for product 2
    {
        productId: "2",
        userId: "user3",
        username: "AliceJohnson",
        rating: 5,
        review: "Love these yoga pants! They are super comfortable and stretchy. Great for yoga practice.",
        date: new Date("2023-04-02"),
    },
    {
        productId: "2",
        userId: "user4",
        username: "BobWilliams",
        rating: 5,
        review: "These pants are amazing quality and fit perfectly! I wear them everywhere.",
        date: new Date("2023-04-05"),
    },
    // Reviews for product 3
    {
        productId: "3",
        userId: "user5",
        username: "EmilyBrown",
        rating: 4,
        review: "Nice shirt, good quality material. The fit is a bit loose for my liking, but overall, I'm satisfied with the purchase.",
        date: new Date("2023-04-10"),
    },
    {
        productId: "3",
        userId: "user6",
        username: "DavidMiller",
        rating: 5,
        review: "I love this shirt! It's so comfortable and versatile. Definitely recommend it.",
        date: new Date("2023-04-15"),
    },
    // Reviews for product 4
    {
        productId: "4",
        userId: "user7",
        username: "OliviaGarcia",
        rating: 4,
        review: "Great shorts for running! They are lightweight and breathable. Only downside is the lack of pockets.",
        date: new Date("2023-04-20"),
    },
    // Reviews for product 5
    {
        productId: "5",
        userId: "user8",
        username: "JamesWilson",
        rating: 5,
        review: "This hoodie is perfect for cooler weather. It's warm, comfortable, and fits great. Highly recommend!",
        date: new Date("2023-04-25"),
    },
    // Reviews for product 6
    {
        productId: "6",
        userId: "user9",
        username: "SophiaLee",
        rating: 5,
        review: "These earbuds are fantastic! The sound quality is excellent, and they connect easily to my devices.",
        date: new Date("2023-05-01"),
    },
    // Reviews for product 7
    {
        productId: "7",
        userId: "user10",
        username: "MichaelMartinez",
        rating: 4,
        review: "Good power bank for the price. It charges my phone quickly and is compact enough to carry around.",
        date: new Date("2023-05-05"),
    },
    // Reviews for product 8
    {
        productId: "8",
        userId: "user11",
        username: "EmmaAnderson",
        rating: 4,
        review: "Nice wallet, good quality leather. It's a bit bulky with all my cards, but overall, I'm satisfied.",
        date: new Date("2023-05-10"),
    },
    // Reviews for product 9
    {
        productId: "9",
        userId: "user12",
        username: "WilliamTaylor",
        rating: 5,
        review: "This backpack is perfect for traveling! It has plenty of room for all my essentials and is very comfortable to wear.",
        date: new Date("2023-05-15"),
    },
    // Reviews for product 10
    {
        productId: "10",
        userId: "user13",
        username: "IsabellaThomas",
        rating: 4,
        review: "Good quality case, provides decent protection for my phone. The clear version looks nice and shows off the phone's design.",
        date: new Date("2023-05-20"),
    },
];

export const paymentMethods = [
    {
        id: "cash_on_delivery",
        name: "Cash on Delivery",
        description: "Pay with cash upon delivery of your order.",
        iconUrl: "/payment-2.png",
    },
    {
        id: "credit_debit_card",
        name: "Credit/Debit Card",
        description:
            "Pay securely with your Visa, Mastercard, or American Express card.",
        iconUrl: "/payment-2.png",
    },
    {
        id: "mobile_financial_services",
        name: "Mobile Financial Services",
        description:
            "Pay conveniently using mobile financial services like bKash, Nagad, or Rocket.",
        iconUrl: "/payment-2.png",
    },
    {
        id: "bank_transfer",
        name: "Bank Transfer",
        description: "Transfer payment directly from your bank account.",
        iconUrl: "/payment-2.png",
    },
    {
        id: "google_pay",
        name: "Google Pay",
        description: "Securely pay with Google Pay.",
        iconUrl: "/payment-2.png",
    },
    {
        id: "apple_pay",
        name: "Apple Pay",
        description: "Securely pay with Apple Pay.",
        iconUrl: "/payment-2.png",
    },
    {
        id: "amazon_pay",
        name: "Amazon Pay",
        description: "Securely pay with Amazon Pay.",
        iconUrl: "/payment-2.png",
    },
    {
        id: "payoneer",
        name: "Payoneer",
        description: "Securely pay with Payoneer.",
        iconUrl: "/payment-2.png",
    },
    {
        id: "paypal",
        name: "PayPal",
        description: "Securely pay with PayPal.",
        iconUrl: "/payment-2.png",
    },
];
