export const categories = [
    {
        name: "Size",
        items: [
            { name: "Small", slug: "small" },
            { name: "Medium", slug: "medium" },
            { name: "Large", slug: "large" },
            { name: "Extra Large", slug: "extra-large" },
            { name: "XXL", slug: "xxl" },
            { name: "XXXL", slug: "xxxl" },
        ],
    },
    {
        name: "Color",
        items: [
            { name: "Red", slug: "red" },
            { name: "Blue", slug: "blue" },
            { name: "Green", slug: "green" },
            { name: "Black", slug: "black" },
            { name: "White", slug: "white" },
            { name: "Yellow", slug: "yellow" },
        ],
    },
    {
        name: "Brand",
        items: [
            { name: "Nike", slug: "nike" },
            { name: "Adidas", slug: "adidas" },
            { name: "Puma", slug: "puma" },
            { name: "Reebok", slug: "reebok" },
            { name: "Under Armour", slug: "under-armour" },
            { name: "New Balance", slug: "new-balance" },
        ],
    },
    {
        name: "Price Range",
        items: [
            { name: "Under $50", slug: "under-50" },
            { name: "$50 - $100", slug: "50-100" },
            { name: "$100 - $200", slug: "100-200" },
            { name: "$200 - $500", slug: "200-500" },
            { name: "$500 - $1000", slug: "500-1000" },
            { name: "Over $1000", slug: "over-1000" },
        ],
    },
    {
        name: "Discount",
        items: [
            { name: "10% Off or More", slug: "10-off" },
            { name: "20% Off or More", slug: "20-off" },
            { name: "30% Off or More", slug: "30-off" },
            { name: "40% Off or More", slug: "40-off" },
            { name: "50% Off or More", slug: "50-off" },
            { name: "60% Off or More", slug: "60-off" },
        ],
    },
    {
        name: "Availability",
        items: [
            { name: "In Stock", slug: "in-stock" },
            { name: "Out of Stock", slug: "out-of-stock" },
        ],
    },
];

export const products = [
    {
        id: "1",
        name: "Men's Running Shoes",
        description: "Lightweight and comfortable running shoes for men.",
        price: 99.99,
        brand: "Nike",
        category: "Footwear",
        color: ["Black", "White", "Blue"],
        size: ["US 9", "US 10", "US 11"],
        images: ["/products/card1.png", "/products/card1.png"],
        thumbnail: "/products/card1.png",
        stockAvailability: "In Stock",
        discount: "10% Off",
        rating: 4.5,
        slug: "mens-running-shoes",
        sku: "NIKE12345",
        weight: 0.5,
        dimensions: {
            length: 30,
            width: 10,
            height: 15,
        },
        tags: ["running", "athletic", "shoes"],
    },
    {
        id: "2",
        name: "Women's Yoga Pants",
        description: "Stretchable and comfortable yoga pants for women.",
        price: 49.99,
        brand: "Adidas",
        category: "Activewear",
        color: ["Black", "Gray", "Purple"],
        size: ["XS", "S", "M", "L"],
        images: ["/products/card2.png", "/products/card2.png"],
        thumbnail: "/products/card2.png",
        stockAvailability: "In Stock",
        slug: "womens-yoga-pants",
        sku: "ADIDAS67890",
        weight: 0.4,
        dimensions: {
            length: 35,
            width: 12,
            height: 18,
        },
        tags: ["yoga", "activewear", "pants"],
    },
    {
        id: "3",
        name: "Men's Casual Shirt",
        description: "Stylish and comfortable casual shirt for men.",
        price: 29.99,
        brand: "Gap",
        category: "Clothing",
        color: ["White", "Blue", "Gray"],
        size: ["S", "M", "L", "XL"],
        images: ["/products/card3.png", "/products/card3.png"],
        thumbnail: "/products/card3.png",
        stockAvailability: "In Stock",
        slug: "mens-casual-shirt",
        sku: "GAP98765",
        weight: 0.3,
        dimensions: {
            length: 25,
            width: 10,
            height: 5,
        },
        tags: ["shirt", "casual", "clothing"],
    },
    {
        id: "4",
        name: "Women's Running Shorts",
        description: "Breathable and lightweight running shorts for women.",
        price: 39.99,
        brand: "Under Armour",
        category: "Activewear",
        color: ["Black", "Pink", "Purple"],
        size: ["XS", "S", "M", "L"],
        images: ["/products/card4.png", "/products/card4.png"],
        thumbnail: "/products/card4.png",
        stockAvailability: "In Stock",
        slug: "womens-running-shorts",
        sku: "UA56789",
        weight: 0.2,
        dimensions: {
            length: 20,
            width: 8,
            height: 3,
        },
        tags: ["running", "activewear", "shorts"],
    },
    {
        id: "5",
        name: "Men's Hoodie",
        description: "Warm and comfortable hoodie for men.",
        price: 79.99,
        brand: "The North Face",
        category: "Clothing",
        color: ["Black", "Gray", "Blue"],
        size: ["S", "M", "L", "XL"],
        images: ["/products/card1.png", "/products/card1.png"],
        thumbnail: "/products/card1.png",
        stockAvailability: "In Stock",
        slug: "mens-hoodie",
        sku: "TNF123",
        weight: 0.6,
        dimensions: {
            length: 40,
            width: 15,
            height: 10,
        },
        tags: ["hoodie", "clothing"],
    },
    {
        id: "6",
        name: "Wireless Bluetooth Earbuds",
        description:
            "High-quality wireless earbuds with Bluetooth connectivity.",
        price: 69.99,
        brand: "Sony",
        category: "Electronics",
        color: ["Black", "White", "Red"],
        size: ["One Size"],
        images: ["/products/card2.png", "/products/card2.png"],
        thumbnail: "/products/card2.png",
        stockAvailability: "In Stock",
        slug: "wireless-bluetooth-earbuds",
        sku: "SONY789",
        weight: 0.1,
        dimensions: {
            length: 5,
            width: 5,
            height: 2,
        },
        tags: ["earbuds", "audio", "electronics"],
    },
    {
        id: "7",
        name: "Portable Power Bank",
        description:
            "Compact and portable power bank for charging devices on the go.",
        price: 29.99,
        brand: "Anker",
        category: "Electronics",
        color: ["Black", "White", "Blue"],
        size: ["One Size"],
        images: ["/products/card3.png", "/products/card3.png"],
        thumbnail: "/products/card3.png",
        stockAvailability: "In Stock",
        slug: "portable-power-bank",
        sku: "ANK123",
        weight: 0.3,
        dimensions: {
            length: 10,
            width: 5,
            height: 2,
        },
        tags: ["power-bank", "electronics"],
    },
    {
        id: "8",
        name: "Men's Leather Wallet",
        description:
            "Classic leather wallet with multiple card slots and a cash compartment.",
        price: 49.99,
        brand: "Fossil",
        category: "Accessories",
        color: ["Black", "Brown"],
        size: ["One Size"],
        images: ["/products/card4.png", "/products/card4.png"],
        thumbnail: "/products/card4.png",
        stockAvailability: "In Stock",
        slug: "mens-leather-wallet",
        sku: "FOSSIL456",
        weight: 0.2,
        dimensions: {
            length: 10,
            width: 8,
            height: 2,
        },
        tags: ["wallet", "accessories"],
    },
    {
        id: "9",
        name: "Travel Backpack",
        description:
            "Durable and spacious backpack for travel and outdoor activities.",
        price: 79.99,
        brand: "Osprey",
        category: "Bags",
        color: ["Black", "Green", "Blue"],
        size: ["One Size"],
        images: ["/products/card2.png", "/products/card2.png"],
        thumbnail: "/products/card2.png",
        stockAvailability: "In Stock",
        slug: "travel-backpack",
        sku: "OSPREY789",
        weight: 1.0,
        dimensions: {
            length: 50,
            width: 30,
            height: 20,
        },
        tags: ["backpack", "bags", "travel"],
    },
    {
        id: "10",
        name: "Smartphone Case",
        description:
            "Protective case for smartphones with shock-absorbing features.",
        price: 19.99,
        brand: "Spigen",
        category: "Accessories",
        color: ["Black", "Clear", "Blue"],
        size: ["One Size"],
        images: ["/products/card1.png", "/products/card1.png"],
        thumbnail: "/products/card1.png",
        stockAvailability: "In Stock",
        slug: "smartphone-case",
        sku: "SPIGEN345",
        weight: 0.1,
        dimensions: {
            length: 15,
            width: 8,
            height: 1,
        },
        tags: ["smartphone-case", "accessories"],
    },
];
